const terrainFeatures = {
  1: "One",
  2: "Two",
  3: "Three",
  4: "Four",
  5: "Five",
  6: "Six",
  7: "Seven",
  8: "Eight",
  9: "Nine",
  10: "Ten",
  11: "Eleven",
  12: "Twelve",
  13: "Thirteen",
  14: "Fourteen",
  15: "Fifteen",
  16: "Sixteen",
  17: "Seventeen",
  18: "Eighteen",
  19: "Nineteen",
  20: "Twenty",
};

const whatsGoingOnRightNow = {
  1: "They lost a fight or had an accident, and are tending their wounded",
  2: "They’re absorbed in eating a meal",
  3: "They’re arguing over some pertinent matter",
  4: "They’re busy trying to repair a broken object or structure of importance to them",
  5: "They’re having some sort of religious ritual",
  6: "They’re resting after hard labor",
  7: "They’re interrogating a prisoner or suspected traitor to the group",
  8: "They’re training or practicing their skills",
  9: "They’re drinking or celebrating some win",
  10: "There’s a tense leadership showdown",
  11: "They’re lolling around in indolent idleness",
  12: "They’re conducting the business of daily life and other duties of common necessity",
};

const whatProblemsDoTheyHave = {
  1: "An ambitious underling plots against the leader or undermines their control",
  2: "They’re arguing over the fair division of some recently-gained spoils",
  3: "Some are seriously ill with a disease",
  4: "The leader is being foolish or irrational, driven by their own desires",
  5: "They’re overconfident and careless",
  6: "They’ve lost some treasure precious to them",
  7: "The underlings are ignoring the leader’s will",
  8: "They’ve been afflicted by some danger of their current environment",
  9: "They’re out of food or some other supply",
  10: "They’re being targeted by some hostile rival or dangerous local denizen",
  11: "They’ve been driven from their usual home by an enemy or a natural hazard",
  12: "Some of their members have been taken prisoner or lost",
};

const twistsAboutTargetOrAllies = {
  1: "They are or have access to spellcasters or mages of some kind",
  2: "They have a useful magical power uncommon to their kind",
  3: "An unusually strong ally serves the group’s leader for its own reasons",
  4: "The group is divided into parties or factions that cooperate poorly with each other",
  5: "Killing them would enrage a seemingly-unrelated person or group",
  6: "They have some reason to mistake the PCs for allies or hirelings",
  7: "One member is a secret traitor in service to some other cause or group",
  8: "Another group would pay very well or be very pleased at the death of the target",
  9: "Eliminating this target would somehow release or remove a check on a dire foe",
  10: "The target wants to get a member of their group killed in a deniable way and will try to use the PCs to do it",
  11: "They’re religious zealots who may or may not have some blessing or affiliation that fits",
  12: "They’re searching for something that the PCs may or may not be able to help them find",
  13: "The leader is desperately in love with one of their underlings or vice-versa",
  14: "They’re tampering with some object or structural feature that’s extremely dangerous",
  15: "They’re foreign to the other examples of their creature type around here, having come from far off for their own reasons",
  16: "They fight in an effective but abnormal way for their type or nature",
  17: "Their leader has ensured that some dire consequence will ensue if they are killed",
  18: "Some portion of the group would really rather not fight but are feeling compelled by their peers or the leader",
  19: "Some other group has a spy or observer who is watching during a potential conflict",
  20: "The leader is an impostor or catspaw of some power that would normally be their enemy and acts as best they can to serve them",
};

const whatsThatBestialMonsterDoing = {
  1: "It’s eaten recently and is lolling around, disinclined to hunt new prey",
  2: "It’s fighting with another of its kind over a mate",
  3: "It’s guarding cubs, eggs, or a recent kill",
  4: "It’s currently hunting something else but might choose to select the PCs as new prey",
  5: "It’s asleep or torpid and has probably chosen a seemingly-safe spot to do so",
  6: "It’s playing after the manner of its kind",
  7: "It’s patrolling its territory to repel intruders or rivals for mates",
  8: "It’s fleeing, having been driven out by a foe or a more powerful rival",
  9: "It licks its wounds after a hard battle, perhaps still surrounded by the corpses of its prey and their remaining belongings",
  10: "It’s digging, marking, or otherwise preparing its new lair and may have a mate helping it do so",
  11: "It’s grooming itself or engaging in behavior specific to its type of creature",
  12: "It’s starving and is ravenous for prey that it might not dare attack in more prosperous times",
};

const wildernessLairComplications = {
  1: "Hazardous flora make up a natural trap for those ignorant of their perils",
  2: "Numerous deadfalls or covered pits have been placed on side paths here",
  3: "The lair is positioned somewhere that has an excellent view of most approaches to it",
  4: "You need to go underwater or through some noxious gas to reach the habitable part of the lair",
  5: "It’s surrounded by some natural peril, radioactive zone, arratu, or other hazard",
  6: "There’s a nest or lair of some dangerous animal obstructing easy entrance, but the occupants know how to deal with them",
  7: "A fearsome local predator has been tamed or pacified and will attack intruders",
  8: "The lair’s built at least partially into some ancient structure or ruin",
  9: "The lair’s inside the hunting territory of some dreadful creature",
  10: "It’s extremely well-concealed amid the terrain",
  11: "Unrelated people are also living in or near it, and disturbing them would be hazardous",
  12: "It’s contaminated with stored magical energy, a damaged Working, or some other curse",
};

const urbanDwellingComplications = {
  1: "An inquisitive neighbor is always watching the place",
  2: "The guards are unusually vigilant and attentive to their duties for some reason",
  3: "The target’s living quarters are uncommonly difficult to access",
  4: "There’s a dangerous beast guarding the grounds of the place",
  5: "The dwelling is unusually well-fortified",
  6: "Servants and minions are thick in the halls",
  7: "The owner has access to some kind of magical ward or divine blessing",
  8: "The place is right next to a very vigilant and dangerous neighbor that will respond to alarms or disorders",
  9: "The interior is mazey, abnormal, or difficult to navigate for some reason",
  10: "Poor repairs or recent damage makes the place dangerous to unknowing outsiders",
  11: "There are several traps or alarms there",
  12: "It’s connected to some kind of underground passages or ancient tunnels",
};

const deepChamberComplications = {
  1: "A dangerous standing magical effect is present in the room",
  2: "Part of the structure is fragile and prone to collapse if damaged",
  3: "There’s some noxious gas or substance tainting certain areas",
  4: "A dangerous fall is possible in some part of the room",
  5: "An ancient guardian risks being awakened by disturbances here",
  6: "Strange ancient engines churn nearby and can cause dire injury to the careless",
  7: "There are secret passages here",
  8: "The room is very vertical in its shape",
  9: "A certain path must be known to safely cross a particularly treacherous surface",
  10: "It’s somehow prone to flooding or currently a swampy mess",
  11: "A valuable object here is extremely fragile",
  12: "Some ancient magic or Deep functionality has been repurposed for a purpose convenient to the current occupants",
};
